name: JuiceShop-Deploy
on:
  workflow_dispatch:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2

        with:
          node-version: "16"

      - name: clone Juice Shop 
        run: git clone https://github.com/juice-shop/juice-shop.git

      - name: run npm install 
      - run : npm install 
        working-directory: juice-shop

      - name: install semgrep 
        run: python3 -m pip install semgrep

      - name: Run Static Anakysis scan 
        run: semgrep --config=auto .
        working-directory: juice-shop
      
      - name: do npm install
        run: npm install -g snyk heroku

      - name: Building docker image 
        run: docker build -t mytest/mytest . 

      - name: Scanning image with snyk 
        run: snyk container test mytest/mytest --file=Dockerfile || true
      
      # - name: Heroku configure 
      #   run: | 
      #     heroku container:login 
      #     export TIME=$(date +%s)
      #     export APPNAME="juiceshop$TIME"
      #     heroku create $APPNAME
      
      # - name: Push image to Heroku registry 
      #   run: heroku container:push web 
      
      # - name: Heroku release image 
      #   run: heroku container:release web

      # - name: Heroku app url 
      #   run: |
      #     heroku info 
      #     #echo "https://$APPNAME.herokuapp.com"



      